// The day the whole system "starts". Nothing planned before this moment is
// scored on the Dashboard, listed in Master, or generated by the recurrence
// engine. Default: 5 Oct 2026, 00:00 India time (= 4 Oct 2026 18:30 UTC).
// Override with TRACKING_START=YYYY-MM-DD in backend/.env if it ever changes.
const IST_MS = (5 * 60 + 30) * 60000;
const raw = process.env.TRACKING_START || "2026-10-05";
const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(raw);
export const TRACKING_START = m
  ? new Date(Date.UTC(+m[1], +m[2] - 1, +m[3]) - IST_MS)
  : new Date(Date.UTC(2026, 9, 5) - IST_MS);

// Raises a Mongo `planned` condition so it never reaches before TRACKING_START.
export function withTrackingFloor(plannedCond) {
  const cond = { ...(plannedCond || {}) };
  if (!cond.$gte || cond.$gte < TRACKING_START) cond.$gte = TRACKING_START;
  return cond;
}
